spring.application.name=JasperAI

#Support Value - deepseek/gigachat
spring.ai.model.chat=gigachat

spring.ai.deepseek.api-key=
spring.ai.deepseek.base-url=https://api.deepseek.com
spring.ai.deepseek.chat.options.model=deepseek-chat
spring.ai.deepseek.chat.options.max-tokens=8192
#spring.ai.deepseek.chat.options.model=deepseek-reasoner
#spring.ai.deepseek.chat.options.max-tokens=60000
spring.ai.deepseek.chat.options.temperature=0.01


spring.ai.gigachat.auth.bearer.api-key=
spring.ai.gigachat.auth.scope=GIGACHAT_API_CORP
spring.ai.gigachat.auth.unsafe-ssl=true
spring.ai.gigachat.chat.options.model=GigaChat-2-Max
spring.ai.gigachat.chat.options.temperature=0.1

jasper.generation.max-attempts=5

logging.level.org.springframework.ai.chat.client.advisor: DEBUG